# Generated by Django 5.0.6 on 2025-02-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_image", models.CharField(blank=True, max_length=100, null=True)),
                ("rating", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=50)),
                ("review", models.TextField()),
            ],
        ),
    ]
