# Generated by Django 5.0.6 on 2025-02-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Star"),
                    (3, "3 Star"),
                    (4, "4 Star"),
                    (5, "5 Star"),
                ]
            ),
        ),
    ]
