# Generated by Django 5.0.6 on 2025-02-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_testimonial_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=100)),
                ("answer", models.TextField()),
            ],
        ),
    ]
