# Generated by Django 5.0.6 on 2025-03-27 20:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_blog_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
